# Generated by Django 2.2.6 on 2019-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='problem_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='problem_tried',
            field=models.IntegerField(default=0),
        ),
    ]
