# Generated by Django 2.2.6 on 2019-10-26 06:31

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.FileField(default=1, upload_to=submission.models.path_to_save),
            preserve_default=False,
        ),
    ]
