# Generated by Django 2.2.6 on 2019-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.IntegerField(default=1),
        ),
    ]
