# Generated by Django 2.2.6 on 2019-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20191026_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.IntegerField(),
        ),
    ]
