# Generated by Django 2.2.6 on 2019-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20191027_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python')], default='cpp', max_length=10),
        ),
    ]
