# Generated by Django 2.2.6 on 2019-10-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20191027_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='lang',
            new_name='language',
        ),
    ]
