# Generated by Django 2.2.6 on 2019-10-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20191028_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python')], default='C++', max_length=10),
        ),
    ]
