# Generated by Django 2.2.6 on 2019-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20191028_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Compilation Error'), (4, 'Time Limit Exceeded'), (5, 'Memory Limit Exceeded')], default=0, max_length=20),
        ),
    ]
