# Generated by Django 2.2.6 on 2019-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20191028_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Compilation Error'), (4, 'Time Limit Exceeded'), (5, 'Memory Limit Exceeded'), (6, 'Run Time Error')], default=0),
        ),
    ]
